---
application:
  name: "imfk"
  project: "imfk"
  organization: "QoveryCommunity"
routers:
- name: "imfk"
  custom_domains:
  - branch: master
    domain: imfk.acme.com
  routes:
  - application_name: "imfk"
    paths:
    - "/*"
